name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy-staging:
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.STAGING_SSH_PASSPHRASE }}
          port: 22
          script: |
            cd /var/www/Vivo-Consulting-AB/
            git pull origin staging
            git status
            sudo ./build.sh

  deploy-production:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
          port: 22
          script: |
            cd /var/www/Vivo-Consulting-AB/
            git pull origin main
            git status
            cd /var/www/Vivo-Consulting-AB
            /usr/local/bin/pnpm install
            /usr/local/bin/pnpm run build
            echo "Restarting vivo-con.service now"
            sudo systemctl restart vivonurse.service
            echo "Build script ended"
